kind: pipeline
name: default

steps:
- name: maven-build
  image: maven:3.6-jdk-11
  commands:
    - mvn clean package #-P MavenCentral
    - ls -lisa ./target

- name: docker-publish
  image: plugins/docker
  settings:
    repo: geopossachs/bootsfaces_showcase
    tags: snapshot
    dockerfile: Dockerfile-wildfly
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: container-reboot
  image: drillster/drone-rsync
  environment:
    RSYNC_KEY:
      from_secret: rsync_key
    RSYNC_USER:
      from_secret: rsync_user
  settings:
    hosts: [ "showcase.bootsfaces.pecer.de" ]
    source: docker-compose.yml
    target: /srv/bootsfaces-showcase/
    secrets: [ rsync_user, rsync_key ]
    script:
      - cd /srv/bootsfaces-showcase/
      - docker-compose pull
      - docker-compose up -d