kind: pipeline
name: default

steps:

- name: gradle-dummy-build-war
  image: openjdk:11-jdk
  commands:
    - ./gradlew -Dorg.gradle.daemon=false -b build.gradle clean war
    - ls -lisa ./build/libs/
  volumes:
  - name: maven-cache
    path: /root/.m2

  # build the ./target/BootsFacesWeb.war
- name: maven-build-war
  image: maven:3.6-jdk-11
  commands:
    - mvn clean package #-P MavenCentral
    - cd ./target/
    - ls -lisa
  volumes:
  - name: maven-cache
    path: /root/.m2

  # push an image to geopossachs/bootsfaces_showcase:{environment}
- name: docker-publish
  when:
    branch:
      - system/production
      - system/stage
  image: plugins/docker
  settings:
    repo: geopossachs/bootsfaces_showcase
    tags: ${DRONE_BRANCH##system/}
    dockerfile: Dockerfile-wildfly
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

  # boot the app on a docker based runtime
- name: container-reboot
  when:
    branch:
      - system/production
      - system/stage
  image: drillster/drone-rsync
  environment:
    RSYNC_KEY:
      from_secret: rsync_key
    RSYNC_USER:
      from_secret: rsync_user
  settings:
    hosts: [ "showcase.bootsfaces.de" ]
    source: ./docker-compose.yml
    target: /srv/bootsfaces-showcase__${DRONE_BRANCH/\//-}/
    #secrets: [ rsync_user, rsync_key ]
    script:
      - cd /srv/bootsfaces-showcase__${DRONE_BRANCH/\//-}/
      - echo VERSION=${DRONE_BRANCH##system/}>.env
      - if [ "${DRONE_BRANCH##system/}" = "production" ]; then echo "PORT=6070" >> .env ; fi
      - if [ "${DRONE_BRANCH##system/}" = "stage" ]; then echo "PORT=6060" >> .env ; fi
      - docker-compose pull
      - docker-compose up -d --remove-orphans


- name: container-reboot
  when:
    branch:
      - system/production
      - system/stage
  image: drillster/drone-rsync
  environment:
    RSYNC_KEY:
      from_secret: master_rsync_key
    RSYNC_USER:
      from_secret: master_rsync_user
  settings:
    hosts: [ "showcase.bootsfaces.net" ]
    port:
      from_secret: master_rsync_port
    source: ./target/BootsFacesWeb.war
    target: /home/tclxd/geopossachs/BootsFacesWeb.war
    #secrets: [ rsync_user, rsync_key ]



volumes:
  - name: maven-cache
    host: 
      path: /temp/drone/m2cache