kind: pipeline
name: default

steps:
- name: maven-build
  image: maven:3.6-jdk-11
  commands:
    - mvn clean package #-P MavenCentral
    - ls -lisa ./target

- name: docker-publish
  image: plugins/docker
  settings:
    repo: geopossachs/bootsfaces_showcase
    tags: snapshot
    dockerfile: Dockerfile-wildfly
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
