kind: pipeline
name: default

steps:
#
- name: gradle-dummy-build-war
  image: openjdk:11-jdk
  commands:
    - ./gradlew --no-daemon -b build.gradle clean war
    - ls -lisa ./build/libs/
  volumes:
  - name: maven-cache
    path: /root/.m2

# build the ./target/BootsFacesWeb.war
- name: maven-build-war
  image: maven:3.6-jdk-11
  commands:
    - mvn clean package #-P MavenCentral
    - cd ./target/
    - ls -lisa
  volumes:
  - name: maven-cache
    path: /root/.m2

# push an image to geopossachs/bootsfaces_showcase:{environment}
- name: mirror__docker-publish
  when:
    repo:
      - geopossachs/BootsFacesWeb
    branch:
      - system/production
      - system/stage
  image: plugins/docker
  settings:
    repo: geopossachs/bootsfaces_showcase
    tags: ${DRONE_BRANCH##system/}
    dockerfile: Dockerfile-wildfly
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

# boot the app on a docker based runtime
- name: mirror__container-reboot
  when:
    repo:
      - geopossachs/BootsFacesWeb
    branch:
      - system/production
      - system/stage
  image: appleboy/drone-ssh
  settings:
    host:
      - showcase.bootsfaces.de
    username:
      from_secret: rsync_user
    key:
      from_secret: rsync_key
    port:
      from_secret: rsync_port
    script:
      - cd /srv/IaC/bootsfaces-showcase__${DRONE_BRANCH/\//-}/
      - docker compose pull
      - docker compose up -d --remove-orphans

#
- name: mirror__publish
  when:
    repo:
      - geopossachs/BootsFacesWeb
    branch:
      - system/production
      - system/stage
  image: appleboy/drone-scp
  settings:
    host: showcase.bootsfaces.net
    username:
      from_secret: master_rsync_user
    key:
      from_secret: master_rsync_key
    port: 
      from_secret: master_rsync_port
    target: /home/tclxd/geopossachs/bootsfaces-showcase__${DRONE_BRANCH/\//-}/
    source: target/BootsFacesWeb.war



volumes:
  - name: maven-cache
    host: 
      path: /temp/drone/m2cache